### ISSUE TITLE
python setup.py install TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not int

### ISSUE THREAD

**Issue by EMRYLMZ1** [EMRYLMZ1/TypeError-_getfullpathname-path-should-be-string-bytes-or-os.PathLike-not-int#1]
Traceback (most recent call last):
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\EMRE\AppData\Local\Temp\easy_install-p6l18_5y\pandas-1.4.2\setup.py", line 651, in <module>
  File "C:\Users\EMRE\AppData\Local\Temp\easy_install-p6l18_5y\pandas-1.4.2\setup.py", line 424, in maybe_cythonize
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\Cython\Build\Dependencies.py", line 1104, in cythonize
    nthreads, initializer=_init_multiprocessing_helper)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\popen_spawn_win32.py", line 67, in __init__
    with open(wfd, 'wb', closefd=True) as to_child:
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 453, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 464, in _ok
    realpath = os.path.normcase(os.path.realpath(path))
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    python_requires='>3.6',
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\pkg_resources\__init__.py", line 768, in resolve
    replace_conflicting=replace_conflicting
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
    return installer(requirement)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 262, in run_setup
    raise
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\EMRE\AppData\Local\Temp\easy_install-p6l18_5y\pandas-1.4.2\setup.py", line 651, in <module>
  File "C:\Users\EMRE\AppData\Local\Temp\easy_install-p6l18_5y\pandas-1.4.2\setup.py", line 424, in maybe_cythonize
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\Cython\Build\Dependencies.py", line 1104, in cythonize
    nthreads, initializer=_init_multiprocessing_helper)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\multiprocessing\popen_spawn_win32.py", line 67, in __init__
    with open(wfd, 'wb', closefd=True) as to_child:
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 453, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\site-packages\setuptools\sandbox.py", line 464, in _ok
    realpath = os.path.normcase(os.path.realpath(path))
  File "C:\Users\EMRE\anaconda3\envs\gpuemre\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not int

I am encountering such an error when you do python setup.py install. Help

**Comment by EMRYLMZ1** [comment]
i think typing pip install panda fixed it
